Replace url

diff --git a/.github/workflows/mirror.yml b/.github/workflows/mirror.yml
--- a/.github/workflows/mirror.yml
+++ b/.github/workflows/mirror.yml
@@ -5,7 +5,7 @@ name: Mirror Site
 # Controls when the workflow will run
 on:
   schedule:
-    - cron: "11 21 * * *"
+    - cron: "41 16 * * *"
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -39,9 +39,9 @@ jobs:
 
       # Download website
       - name: Download the files
-        run: wget -m --retry-connrefused --tries=20 --no-host-directories --directory-prefix="www" --exclude-directories="/wp-json,/wp-admin" --regex-type 'pcre' --reject-regex '.*\?(?!ver).*' --wait 1 https://chriskthomas.com/
+        run: wget -m --retry-connrefused --tries=20 --no-host-directories --directory-prefix="www" --exclude-directories="/wp-json,/wp-admin" --regex-type 'pcre' --reject-regex '.*\?(?!ver).*' --wait 1 https://www.ftcunion.org/
       - name: Download 404
-        run: wget --content-on-error --directory-prefix="www" https://chriskthomas.com/404.html || echo "Expexted error"
+        run: wget --content-on-error --directory-prefix="www" https://www.ftcunion.org/404.html || echo "Expexted error"
 
       - name: Setup Pages
         uses: actions/configure-pages@v5
@@ -52,9 +52,7 @@ jobs:
       - name: Remove query strings from file names
         run: .github/bin/cleanup-querystrings.py
       - name: Remove domain from URLs # breaks if you have the domain in the content or have http links
-        run: find ./dist/ -type f -exec sed -i -E 's;(https:)?//chriskthomas.com/?;/;g' {} \;
-      - name: Delete comments blocks in posts # breaks if you have a section inside the comments section
-        run: find ./dist/ -type f -name 'index.html' -exec perl -i -0777pe 's;<section id="comments".*?</section>;;s' {} \;
+        run: find ./dist/ -type f -exec sed -i -E 's;(https:)?//www.ftcunion.org;https://ftcunion.github.io;g' {} \;
       - name: Copy robots.txt
         run: cp robots.txt dist/
 
